# Generated by Django 5.0.1 on 2024-02-17 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('location', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ResourceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='STTModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.TextField(verbose_name='access_token')),
                ('refresh', models.TextField(verbose_name='refresh_token')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('about', models.TextField(blank=True, null=True, verbose_name='about')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='country')),
                ('area', models.CharField(blank=True, max_length=100, null=True, verbose_name='area')),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True, verbose_name='phone_number')),
                ('website', models.URLField(blank=True, null=True, verbose_name='website')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='address')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('isbn', models.CharField(help_text='ISBN can be a minimum of 10 and a maximum of 17 characters', max_length=13, verbose_name='ISBN')),
                ('pages', models.IntegerField(default=0, verbose_name='Pages Count')),
                ('key_words', models.TextField(verbose_name='key_words')),
                ('about', models.TextField(verbose_name='about')),
                ('author', models.TextField(verbose_name='author')),
                ('publisher', models.CharField(blank=True, max_length=255, null=True, verbose_name='publisher')),
                ('published_year', models.CharField(max_length=20, verbose_name='published_year')),
                ('language', models.CharField(choices=[('UzbekLatin', 'Uzbek-Latin'), ('UzbekKiril', 'Uzbek-Kiril'), ('Russian', 'Russian'), ('English', 'English')], default='UzbekLatin', max_length=25, verbose_name='language')),
                ('file', models.FileField(help_text='Resurs fayli', upload_to='files/%Y/%m/%d/', verbose_name='file')),
                ('image', models.ImageField(help_text='Resurs rasmi', upload_to='images/%Y/%m/%d/', verbose_name='image')),
                ('permission', models.CharField(choices=[('public', 'public'), ('private', 'private')], max_length=10, verbose_name='permission')),
                ('download_count', models.IntegerField(default=0, verbose_name='download_count')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lib.category')),
                ('library', models.ManyToManyField(blank=True, help_text='Library', to='lib.library')),
                ('resource_area', models.ForeignKey(blank=True, help_text='Resource Area', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lib.resourcearea')),
                ('resource_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lib.resourcetype')),
                ('university', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lib.university')),
            ],
        ),
    ]
