# Generated by Django 5.0.1 on 2024-02-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='latitude',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='longitude',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='phone_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
