# Generated by Django 5.0.1 on 2024-02-27 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0002_book_reprint'),
        ('lib', '0002_library_latitude_library_longitude_and_more'),
    ]

    operations = [
    ]
