# Generated by Django 5.0.1 on 2024-02-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0003_merge_20240227_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=41.316808, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='library',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=69.271821, max_digits=9),
            preserve_default=False,
        ),
    ]
