# Generated by Django 5.0.1 on 2024-02-28 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0003_merge_20240227_1437'),
        ('lib', '0004_alter_library_latitude_alter_library_longitude'),
    ]

    operations = [
    ]
