# Generated by Django 5.0.1 on 2024-03-15 11:17

import lib.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0006_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=20, unique=True, validators=[lib.validators.validate_isbn], verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='reprint',
            field=models.BooleanField(default=False, help_text="Agar kitob qayta nashr qilingan bo'lsa qayta nashr yilini kiriting", verbose_name='reprint'),
        ),
    ]
