# Generated by Django 5.0.1 on 2024-03-27 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0008_category_name_en_category_name_ru_category_name_uz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name': 'Library', 'verbose_name_plural': 'Libraries'},
        ),
        migrations.AlterModelOptions(
            name='resourcearea',
            options={'verbose_name': 'Resource Area', 'verbose_name_plural': 'Resource Areas'},
        ),
        migrations.AlterModelOptions(
            name='resourcetype',
            options={'verbose_name': 'Resource Type', 'verbose_name_plural': 'Resource Types'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'University', 'verbose_name_plural': 'Universities'},
        ),
    ]
