# Generated by Django 5.0.1 on 2024-04-04 08:17

import lib.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0009_alter_book_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[lib.validators.validate_isbn], verbose_name='ISBN'),
        ),
    ]
