# Generated by Django 5.0.1 on 2025-03-18 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_searchhistory_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='timestamp',
        ),
    ]
